# Generated by Django 2.2.7 on 2019-11-21 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workspace', '0002_auto_20191121_1804'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('fc0d4f7c-04e4-4023-b286-e4a96c65659f'), primary_key=True, serialize=False)),
                ('related_login', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('related_workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workspace.Workspace')),
            ],
            options={
                'db_table': 'memberships',
                'unique_together': {('related_login', 'related_workspace')},
            },
        ),
    ]
