# Generated by Django 2.2.7 on 2019-11-24 09:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspace', '0002_auto_20191121_1804'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=150)),
                ('related_workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workspace.Workspace')),
            ],
            options={
                'db_table': 'products',
                'unique_together': {('related_workspace', 'code')},
            },
        ),
    ]
