# Generated by Django 2.2.7 on 2019-11-20 05:17

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
                name='Workspace',
                fields=[
                    ('id', models.UUIDField(default=uuid.UUID('0711a837-c5b9-43a5-a76d-d0a9929212eb'), primary_key=True,
                                            serialize=False)),
                    ('description', models.CharField(max_length=30)),
                    ('related_login',
                     models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ],
                options={
                    'db_table': 'workspaces',
                },
        ),
    ]
