# Generated by Django 2.2.7 on 2019-11-20 09:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='description',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c309e2cd-6789-4e09-bf5d-9b3c6f0ad52f'), primary_key=True, serialize=False),
        ),
    ]
