# Generated by Django 2.2.7 on 2019-11-29 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0002_auto_20191128_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
