# Generated by Django 2.2.7 on 2019-11-29 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0003_auto_20191129_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
